2021-07-10 15:18:58,549 13684 INFO ? odoo: Odoo version 14.0-20210710 
2021-07-10 15:18:58,549 13684 INFO ? odoo: Using configuration file at D:\Student_Time\Godoo\server\odoo.conf 
2021-07-10 15:18:58,549 13684 INFO ? odoo: addons paths: ['D:\\Student_Time\\Godoo\\server\\odoo\\addons', 'c:\\users\\zhao\\appdata\\local\\openerp s.a\\odoo\\addons\\14.0', 'd:\\student_time\\godoo\\server\\odoo\\addons'] 
2021-07-10 15:18:58,549 13684 INFO ? odoo: database: zhaohh@localhost:5432 
2021-07-10 15:18:59,349 13684 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at D:\Student_Time\Godoo\thirdparty\wkhtmltopdf.exe 
2021-07-10 15:18:59,840 13684 INFO ? odoo.service.server: Initiating shutdown 
2021-07-10 15:18:59,840 13684 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2021-07-10 15:19:01,320 2632 INFO ? odoo: Odoo version 14.0-20210710 
2021-07-10 15:19:01,320 2632 INFO ? odoo: Using configuration file at D:\Student_Time\Godoo\server\odoo.conf 
2021-07-10 15:19:01,320 2632 INFO ? odoo: addons paths: ['D:\\Student_Time\\Godoo\\server\\odoo\\addons', 'c:\\users\\zhao\\appdata\\local\\openerp s.a\\odoo\\addons\\14.0', 'd:\\student_time\\godoo\\server\\odoo\\addons'] 
2021-07-10 15:19:01,320 2632 INFO ? odoo: database: zhaohh@localhost:5432 
2021-07-10 15:19:01,464 2632 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at D:\Student_Time\Godoo\thirdparty\wkhtmltopdf.exe 
2021-07-10 15:19:01,558 2632 INFO ? odoo.service.server: HTTP service (werkzeug) running on EvoComputer:8069 
2021-07-10 15:19:09,324 2632 INFO ? odoo.http: HTTP Configuring static files 
2021-07-10 15:19:13,398 2632 INFO ? odoo.sql_db: Connection to the database failed 
2021-07-10 15:19:13,400 2632 INFO ? werkzeug: 127.0.0.1 - - [10/Jul/2021 15:19:13] "GET / HTTP/1.1" 500 - 0 0.000 4.063
2021-07-10 15:19:13,404 2632 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "D:\Student_Time\Godoo\python\lib\site-packages\werkzeug\serving.py", line 306, in run_wsgi
    execute(self.server.app)
  File "D:\Student_Time\Godoo\python\lib\site-packages\werkzeug\serving.py", line 294, in execute
    application_iter = app(environ, start_response)
  File "D:\Student_Time\Godoo\server\odoo\service\server.py", line 441, in app
    return self.app(e, s)
  File "D:\Student_Time\Godoo\server\odoo\service\wsgi_server.py", line 124, in application
    return application_unproxied(environ, start_response)
  File "D:\Student_Time\Godoo\server\odoo\service\wsgi_server.py", line 99, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "D:\Student_Time\Godoo\server\odoo\http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "D:\Student_Time\Godoo\server\odoo\http.py", line 1272, in __call__
    return self.app(environ, start_wrapped)
  File "D:\Student_Time\Godoo\python\lib\site-packages\werkzeug\middleware\shared_data.py", line 220, in __call__
    return self.app(environ, start_response)
  File "D:\Student_Time\Godoo\server\odoo\http.py", line 1440, in dispatch
    self.setup_db(httprequest)
  File "D:\Student_Time\Godoo\server\odoo\http.py", line 1363, in setup_db
    httprequest.session.db = db_monodb(httprequest)
  File "D:\Student_Time\Godoo\server\odoo\http.py", line 1528, in db_monodb
    dbs = db_list(True, httprequest)
  File "D:\Student_Time\Godoo\server\odoo\http.py", line 1495, in db_list
    dbs = odoo.service.db.list_dbs(force)
  File "D:\Student_Time\Godoo\server\odoo\service\db.py", line 384, in list_dbs
    with closing(db.cursor()) as cr:
  File "D:\Student_Time\Godoo\server\odoo\sql_db.py", line 675, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "D:\Student_Time\Godoo\server\odoo\sql_db.py", line 248, in __init__
    self._cnx = pool.borrow(dsn)
  File "D:\Student_Time\Godoo\server\odoo\sql_db.py", line 558, in _locked
    return fun(self, *args, **kwargs)
  File "D:\Student_Time\Godoo\server\odoo\sql_db.py", line 626, in borrow
    **connection_info)
  File "D:\Student_Time\Godoo\python\lib\site-packages\psycopg2\__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused (0x0000274D/10061)
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused (0x0000274D/10061)
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432? - - -
2021-07-10 15:19:17,501 2632 INFO ? odoo.sql_db: Connection to the database failed 
2021-07-10 15:19:17,501 2632 INFO ? werkzeug: 127.0.0.1 - - [10/Jul/2021 15:19:17] "GET /favicon.ico HTTP/1.1" 500 - 0 0.000 4.064
2021-07-10 15:19:17,501 2632 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "D:\Student_Time\Godoo\python\lib\site-packages\werkzeug\serving.py", line 306, in run_wsgi
    execute(self.server.app)
  File "D:\Student_Time\Godoo\python\lib\site-packages\werkzeug\serving.py", line 294, in execute
    application_iter = app(environ, start_response)
  File "D:\Student_Time\Godoo\server\odoo\service\server.py", line 441, in app
    return self.app(e, s)
  File "D:\Student_Time\Godoo\server\odoo\service\wsgi_server.py", line 124, in application
    return application_unproxied(environ, start_response)
  File "D:\Student_Time\Godoo\server\odoo\service\wsgi_server.py", line 99, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "D:\Student_Time\Godoo\server\odoo\http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "D:\Student_Time\Godoo\server\odoo\http.py", line 1272, in __call__
    return self.app(environ, start_wrapped)
  File "D:\Student_Time\Godoo\python\lib\site-packages\werkzeug\middleware\shared_data.py", line 220, in __call__
    return self.app(environ, start_response)
  File "D:\Student_Time\Godoo\server\odoo\http.py", line 1440, in dispatch
    self.setup_db(httprequest)
  File "D:\Student_Time\Godoo\server\odoo\http.py", line 1363, in setup_db
    httprequest.session.db = db_monodb(httprequest)
  File "D:\Student_Time\Godoo\server\odoo\http.py", line 1528, in db_monodb
    dbs = db_list(True, httprequest)
  File "D:\Student_Time\Godoo\server\odoo\http.py", line 1495, in db_list
    dbs = odoo.service.db.list_dbs(force)
  File "D:\Student_Time\Godoo\server\odoo\service\db.py", line 384, in list_dbs
    with closing(db.cursor()) as cr:
  File "D:\Student_Time\Godoo\server\odoo\sql_db.py", line 675, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "D:\Student_Time\Godoo\server\odoo\sql_db.py", line 248, in __init__
    self._cnx = pool.borrow(dsn)
  File "D:\Student_Time\Godoo\server\odoo\sql_db.py", line 558, in _locked
    return fun(self, *args, **kwargs)
  File "D:\Student_Time\Godoo\server\odoo\sql_db.py", line 626, in borrow
    **connection_info)
  File "D:\Student_Time\Godoo\python\lib\site-packages\psycopg2\__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused (0x0000274D/10061)
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused (0x0000274D/10061)
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432? - - -
2021-07-10 16:07:51,210 2632 INFO ? odoo.service.server: Initiating shutdown 
2021-07-10 16:07:51,210 2632 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
